<a href="https://colab.research.google.com/github/WalterSantana07/IMC_CSV/blob/main/IMC_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd

# Leitura do arquivo CSV
data = pd.read_csv('DATASET.CSV', sep=";")

def calcular_imc(massa, altura):
    imc = massa / (altura ** 2)
    return imc

# Interação sobre cada linha do dataset!!!

for index, row in data.iterrows():
    primeiro_nome = row["Primeiro Nome"].upper().strip()
    sobrenomes = row['Sobrenomes'].upper().strip()
    nome_completo = f"{primeiro_nome} {sobrenomes}"

# Verificar se os valores de Peso e Altura são válidos
    massa = row['Peso (kg)']
    altura = row['Altura (m)']

# Verificar se os valores de massa e altura são strings
    if isinstance(massa, str):
        try:
            massa = float(massa.replace(",","."))
        except ValueError:
            print(f"Erro: Valor inválido para a massa em{nome_completo}. Ignorando registro.")
            continue

    if isinstance(altura, str):
        try:
            altura = float(altura.replace(",","."))
        except ValueError:
            print(f"Erro: Valor inválido para a altura em{nome_completo}. Ignorando registro.")
            continue

# Calcular o IMC
    imc = calcular_imc(massa, altura)

# Imprimir nome completo e IMC formatado
    print("{:<25} {:.2f}".format(nome_completo, imc).replace('.' ,','))

FELIPE NEVES              24,72
SANDRO BARBOSA            30,24
MAYCON FERREIRA           30,19
JEFERSON OLIVEIRA         26,14
MANUEL MATTOS             19,46
EMANUEL COSTA             33,76
ISIS DE  DEUS             23,05
MARIA BEZERRA             20,83
ALESSANDRO CEU            20,76
SANDRO BARBOSA            31,62
ALMIR VALENTE             27,12
BRUNO FILHO               25,21
MARTA OLIVEIRA            21,48
MICHELE BATISTA           23,53
ALEX MARIO AS             22,81
DANIEL ALEXANDRE          17,06
MANUELLA PEREIRA          23,93
MATHEUS SILVA             22,85
GIUDERLAN NETO            20,47
GEISA FERREIRA            27,57
NEYMAR JOSEFINO           35,11
JOÃO MICHELANGO           63,29
GABRIELA XAVIER           20,07
MICHELANGELO DE LA BUENA  27,70
IVANOR TOSTADO            26,19
CIENNE CONCEIÇÃO          22,74
ARTHUR SANTANA            21,57
AMARO LUIZ                12,54
ALZENRAU SILVA            16,75
CAIO SENA                 28,27
ROMILDO DA SILVA          29,75
LINDOMAR CATILLO          29,14
FELIZBERTO DA  FELICIDADE 25,00
CAROLINE DA  BOA MENTE    22,32
BRUNA GIUSEPPE            23,70
CARLOS MAGNO              35,68
ADAILTON FERREIRA         21,87
JANDERSSON ALMEIDA        26,60
JOAO JOAQUIM JOÉ DA  SILVA 27,45
ALLAN SANTANA             22,24
DANIELLE SANTOS           20,99
VALDEVINO SOARES          21,33
MARIA PEREIRA             10,05
IVANORVILSON ALBERTO      24,78
CAMELIA JOSELINA          63,49
MEDINCHINA CASAIS         32,23
ALCEBÍADES ASSUNÇÃO       26,54
MASHA ALCÂNTARA           24,92
LIVIA DUARTE              25,71
ROMERSON SIMPSON SILVA    29,42
MIRELLE DA FONSECA FILHA  22,82
SREGIO CARVALHO           9,80
FILADÉLFIO ALFRÔNIO       25,83
MARCOS SILVA              24,27
AFREIM ISOTOPO            34,60
AGATHA BARRETO  DA  SILVA 19,13
EMMANOEL JUNIOR           30,39
ELIZA TRINDADE            24,41
AMINOÃ GABRIELA FERRAZ    17,88
MELISSA FAGUNDES          33,20
DEAN WINCHESTER           34,93
LIUMAR SANTOS OLIVEIRA    26,84
ADALFREDA DA FERREIRA     20,52
JEAN SANTOS               17,88
ANITA OLIVEIRA            nan
JEANE SANTANA             16,74
PABLO VITTAR              0,00
WELITON VIANA             23,46
QUIXOTE DE LA MANCHA      24,93
ARTHUR CARVALHO  JOSE     31,98
ELIANE SANTOS             22,22
EZRAEL MARTINS            19,47
DULCINESIA DEL TROBOSO    20,65
LEONARDO OLIVEIRA  CASTRO 17,28
ALDIRAN SOUSA             19,95
JOSEFINA BEZERRA  OLIVEIRA 28,08
PIRLO JAMES SILVA         31,90
CAIO CORREIRA  SILVA      24,10
GILMAR DE   SANTANA       30,85
JOSEFA SERAFINA           23,67
CAMELORO CRISPIM          17,07
POLICARPO QUARESMA        35,54
BASKARA DA SILVA FERREIRA 25,20
FIUKI FILHO               21,95
FÁTIMA BERNARDES          19,22
SERGIO MALANDRO           29,31
THEO FARIAS               30,70
WALLACE BONNER            28,77
YUMI BACHIÓ               25,67
EMILY SOUZA RIBEIRO       23,90
WHIND PIAUÍ               23,94
ALANE SILVA               17,34
LUANA LIMA  FERREIRA      35,64
INOSWALDO KAMACHO         57,69
LUNA LUNARA LUA           20,23
HULK JOSE                 24,65
MARIA GOMES               23,85
PAULO ROCHA               24,52
LUANE SANTANA TEIXEIRA    22,57